package com.example.springdatadynamo.domain;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

public class DynamoId implements Serializable {
	private static final long serialVersionUID = 1L;
	
	@DynamoDBAutoGeneratedKey
	private String PK;
	private String SK;
	
	@DynamoDBHashKey
	public String getPK() {
		return PK;
	}
	public void setPK(String pK) {
		PK = pK;
	}
	
	@DynamoDBRangeKey
	public String getSK() {
		return SK;
	}
	public void setSK(String sK) {
		SK = sK;
	}
}
